// flow-typed signature: 38aff43dc9bc5d1b0a4ff58bbb75e83f
// flow-typed version: <<STUB>>/babel-plugin-module-resolver_v2.4.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-module-resolver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-module-resolver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-module-resolver/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-module-resolver/lib/mapToRelative' {
  declare module.exports: any;
}

declare module 'babel-plugin-module-resolver/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-module-resolver/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-module-resolver/lib/index'>;
}
declare module 'babel-plugin-module-resolver/lib/mapToRelative.js' {
  declare module.exports: $Exports<'babel-plugin-module-resolver/lib/mapToRelative'>;
}
declare module 'babel-plugin-module-resolver/lib/utils.js' {
  declare module.exports: $Exports<'babel-plugin-module-resolver/lib/utils'>;
}
