// flow-typed signature: ca7a934002328ca0cc9f81a5d7ac022a
// flow-typed version: <<STUB>>/eslint-plugin-react-app_v1.0.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-react-app/config' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-app/plugins' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-react-app/config.js' {
  declare module.exports: $Exports<'eslint-plugin-react-app/config'>;
}
declare module 'eslint-plugin-react-app/index' {
  declare module.exports: $Exports<'eslint-plugin-react-app'>;
}
declare module 'eslint-plugin-react-app/index.js' {
  declare module.exports: $Exports<'eslint-plugin-react-app'>;
}
declare module 'eslint-plugin-react-app/plugins.js' {
  declare module.exports: $Exports<'eslint-plugin-react-app/plugins'>;
}
