// flow-typed signature: a5a23660c42ddf58c66d1ca47cf8af6d
// flow-typed version: <<STUB>>/eslint-import-resolver-babel-module_v2.2.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-import-resolver-babel-module'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-import-resolver-babel-module' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-import-resolver-babel-module/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-import-resolver-babel-module/src/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-babel-module/src/index'>;
}
