// flow-typed signature: e5ce51693475731bdad16b6fe10cf236
// flow-typed version: <<STUB>>/eslint-config-mostaza-react_v1.14.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-mostaza-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-mostaza-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-mostaza-react/rules' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-mostaza-react/index' {
  declare module.exports: $Exports<'eslint-config-mostaza-react'>;
}
declare module 'eslint-config-mostaza-react/index.js' {
  declare module.exports: $Exports<'eslint-config-mostaza-react'>;
}
declare module 'eslint-config-mostaza-react/rules.js' {
  declare module.exports: $Exports<'eslint-config-mostaza-react/rules'>;
}
