// flow-typed signature: 239b0d7eae07d0e049ef2088d2bb39cb
// flow-typed version: <<STUB>>/react-native-sound_vgit+https://github.com/zmxv/react-native-sound.git/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-sound'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-sound' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-sound/sound' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-sound/sound.js' {
  declare module.exports: $Exports<'react-native-sound/sound'>;
}
